test

diff --git a/.github/workflows/file-check.yml b/.github/workflows/file-check.yml
--- a/.github/workflows/file-check.yml
+++ b/.github/workflows/file-check.yml
@@ -6,15 +6,15 @@ on:
 jobs:
   check:
     runs-on: ubuntu-latest
+    env:
+      WHITE_LIST: "piecehealth"
     steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      - name: Check out repository code
-        uses: actions/checkout@v3
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+      - run: |
+        CHANGED_FILES=$(git diff --name-only $(git merge-base main HEAD))
+
+        if echo "$CHANGED_FILES" | grep -q --include='*.yml' '^config/locales/generated/'; then
+          if echo "$WHITE_LIST" | grep -qw "${{ github.actor }}"; then
+            echo "Error: User ${{ github.actor }} is not authorized to make changes."
+            exit 1
+          fi
+        fi
